export default {
  title: "Florian Zeba",
  shortTitle: "FZeba",
  description: "Data & AI Architect focused on enterprise AI applications, data engineering, Microsoft Fabric, software architecture, cloud platforms, and practical technical writing.",
  url: "https://www.fzeba.com",
  author: {
    name: "Florian Zeba",
    email: "hello@fzeba.com",
    jobTitle: "Data & AI Architect",
    image: "/assets/profile.webp",
  },
  language: "en-GB",
  locale: "en_GB",
  defaultImage: "/assets/social-card.png",
  defaultImageAlt: "Florian Zeba - Data and AI Architect",
  keywords: [
    "Florian Zeba",
    "Data & AI Architect",
    "data engineering",
    "AI applications",
    "enterprise AI",
    "Microsoft Fabric",
    "software architecture",
    "cloud architecture",
    "technical blog",
  ],
  topics: [
    "Data engineering",
    "Artificial intelligence",
    "Enterprise software architecture",
    "Microsoft Fabric",
    "Cloud architecture",
    "Machine learning",
    "Backend development",
    "Automation",
  ],
  nav: [
    { text: "Home", url: "/" },
    { text: "Posts", url: "/posts/" },
    { text: "Projects", url: "/projects/" },
    { text: "Search", url: "/search/" },
  ],
  social: [
    { name: "GitHub",   url: "https://github.com/flnzba" },
    { name: "LinkedIn", url: "https://www.linkedin.com/in/florian-zeba/" },
  ],
};
