export default {
  title: "Florian Zeba",
  shortTitle: "FZeba",
  description: "Principal Enterprise Architect for Data & AI. I design the platforms enterprises run their data on, and still write the pipelines that fill them.",
  url: "https://www.fzeba.com",
  author: {
    name: "Florian Zeba",
    email: "florian@fzeba.com",
    jobTitle: "Principal Enterprise Architect, Data & AI",
    image: "/assets/profile.webp",
  },
  language: "en-GB",
  locale: "en_GB",
  defaultImage: "/assets/social-card.png",
  defaultImageAlt: "Florian Zeba - Data and AI Architect",
  keywords: [
    "Florian Zeba",
    "Data & AI Architect",
    "data engineering",
    "AI applications",
    "enterprise AI",
    "Microsoft Fabric",
    "software architecture",
    "cloud architecture",
    "technical blog",
  ],
  topics: [
    "Data engineering",
    "Artificial intelligence",
    "Enterprise software architecture",
    "Microsoft Fabric",
    "Cloud architecture",
    "Machine learning",
    "Backend development",
    "Automation",
  ],
  nav: [
    { text: "Home", url: "/" },
    { text: "Projects", url: "/projects/" },
    { text: "Research", url: "/research/" },
    { text: "Posts", url: "/posts/" },
    { text: "Consulting", url: "/consulting/" },
    { text: "About", url: "/about/" },
    { text: "CV", url: "/cv/" },
    { text: "Search", url: "/search/" },
  ],
  social: [
    { name: "GitHub",   url: "https://github.com/flnzba" },
    { name: "LinkedIn", url: "https://www.linkedin.com/in/florian-zeba/" },
  ],
};
